"use client";

import React, { useState } from "react";
import { Swiper, SwiperProps, SwiperSlide } from "swiper/react";
import imageIa1 from "../../public/assets/ia1.png";
import imageIa2 from "../../public/assets/ia2.png";
import img1 from "../../public/assets/img1.webp";
import img2 from "../../public/assets/img2.png";
import img3 from "../../public/assets/img3.png";
import img4 from "../../public/assets/img4.webp";
import img5 from "../../public/assets/img5.jpg";
import img6 from "../../public/assets/img6.webp";

import CardHome from "./CardHome";
import { Slider } from "..";
import Image from "next/image";

const Section2 = () => {
  const settings: SwiperProps = {
    grabCursor: true,
    loop: true,
    effect: "coverflow",
    centeredSlides: true,
    slidesPerView: "auto",
    coverflowEffect: {
      rotate: 50,
      stretch: 3,
      depth: 100,
      modifier: 1,
      slideShadows: true,
    },
  };

  return (
    <>
      <section className="hero mt-36  px-32 ">
        <div className="flex flex-wrap justify-evenly ">
          <CardHome
            image={imageIa1}
            text="Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature."
            title="IA GENERATE IMAGE"
          />
          <CardHome
            image={imageIa2}
            text="Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots."
            title="IA GENERATE IMAGE"
          />
        </div>
        <div className="flex justify-center w-full items-center mt-40">
          <p className="text-[24px]  text-font-card mt-4">
            Some images generated by IA
          </p>
        </div>
        <div className="flex mt-28 px-36 ">
          <Slider settings={settings}>
            {fotos.map((f, i) => (
              <SwiperSlide key={i}>
                <div className={`h-[500px] w-[700px]`}>
                  <Image
                    src={f.img}
                    layout="fill"
                    alt="Picture of the author"
                    quality={100}
                  />
                </div>
              </SwiperSlide>
            ))}
          </Slider>
        </div>
      </section>
    </>
  );
};

export default Section2;

const fotos = [
  { img: img1 },
  { img: img2 },
  { img: img3 },
  { img: img4 },
  { img: img5 },
  { img: img6 },
];
