"use client";

import { Swiper, SwiperProps, SwiperSlide } from "swiper/react";
import imageIa1 from "../../public/assets/ia1.png";
import imageIa2 from "../../public/assets/ia2.png";
import img1 from "../../public/assets/img1.webp";
import img2 from "../../public/assets/img2.png";
import img3 from "../../public/assets/img3.png";
import img4 from "../../public/assets/img4.webp";
import img5 from "../../public/assets/img5.jpg";
import img6 from "../../public/assets/img6.webp";
import { CardHome } from "@/components";
import { Slider } from "..";
import Image from "next/image";
import { Grab } from "lucide-react";
import styles from "./animationCard.module.css";
import { useState } from "react";

const Section2 = () => {
  const [showIconHover, setshowIconHover] = useState(false);
  const settings: SwiperProps = {
    grabCursor: true,
    loop: true,
    effect: "coverflow",
    centeredSlides: true,
    slidesPerView: "auto",
    coverflowEffect: {
      rotate: 50,
      stretch: 3,
      depth: 100,
      modifier: 1,
      slideShadows: true,
    },
  };

  return (
    <>
      <section className="hero mt-36  px-32 ">
        <div className="flex flex-wrap justify-evenly ">
          <CardHome
            image={imageIa1}
            text="Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature."
            title="IA GENERATE IMAGE"
          />
          <CardHome
            image={imageIa2}
            text="Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots."
            title="IA GENERATE IMAGE"
          />
        </div>
        <div
          className={`${styles["border-gradient"]} flex justify-center w-fit items-center mx-auto pb-3 mt-40`}
        >
          <p className="text-[24px]  text-font-card mt-4">
            Some images generated by IA
          </p>
        </div>

        <div
          className="flex flex-col mt-24 px-36 "
          onMouseEnter={() => setshowIconHover(true)}
          onMouseLeave={() => setshowIconHover(false)}
        >
          <div
            className={`${
              showIconHover ? styles.showIcon : ""
            } flex justify-center   animate-rotate opacity-0`}
          >
            <Grab color="#9b9b9b" size={30} />
          </div>
          <Slider settings={settings}>
            {fotos.map((f, i) => (
              <SwiperSlide key={i}>
                <div className={`h-[500px] w-[700px]`}>
                  <Image
                    src={f.img}
                    layout="fill"
                    alt="Picture of the author"
                    quality={100}
                  />
                </div>
              </SwiperSlide>
            ))}
          </Slider>
        </div>
      </section>
    </>
  );
};

export default Section2;

const fotos = [
  { img: img1 },
  { img: img2 },
  { img: img3 },
  { img: img4 },
  { img: img5 },
  { img: img6 },
];
